### ISSUE TITLE
Combine Redeemable Stake Visualizations on Hatch View

### ISSUE THREAD

**Issue by LinuxIsCool** [TECommons/Token-Log-Hatch-Params#1]
The Hatch View should have the stacked bar charts containing 
1. Redeemable Stake 
2. Cultural Tribute
3. Hatch Tribute

This means, remove the funding pools vis from the Impact Hours Formula Section. Put the impact hours data where the current funding pools vis is.

**Comment by GriffGreen** [comment]
this was discussed about 20 minutes in to the TE Labs call on Jan 29th
