### ISSUE TITLE
Add a few print outs for what the dandelion params mean to the output

### ISSUE THREAD

**Issue by GriffGreen** [TECommons/Token-Log-Hatch-Params#11]
From:
https://www.notion.so/TEC-Models-Spec-d24bdea227324576b04c88871aa616c4

It costs _______wxDAI to make a proposal

Votes will be voted on for _______ days

TECH token holders will have _____ Days to exit the DAO if they don't like the result of a vote (as long as they don't vote yes).

There can be a maximum of ___________ votes per year. 

A proposal that passes can be executed __________ days after it was proposed.

**Comment by LinuxIsCool** [comment]
Consider using panel markdown or html rendering functionality. https://panel.holoviz.org/reference/panes/HTML.html#panes-gallery-html
