### ISSUE TITLE
Zoom into the part of the IH chart that matters most

### ISSUE THREAD

**Issue by GriffGreen** [TECommons/Token-Log-Hatch-Params#13]
Turn this 
<img width="934" alt="Screen Shot 2021-02-03 at 4 55 21 PM" src="https://user-images.githubusercontent.com/14945613/106814763-2f8d6580-6673-11eb-8df2-9e7b080d4e23.png">

Into just this: 

<img width="361" alt="Screen Shot 2021-02-03 at 4 55 26 PM" src="https://user-images.githubusercontent.com/14945613/106814761-2e5c3880-6673-11eb-9c34-391a689f2fb4.png">

**Comment by LinuxIsCool** [comment]
This can be changed in the holoviews object that is being rendered.

**Comment by LinuxIsCool** [comment]
All of the data is loaded in from a data sheet. See the loading functions in tech.py and the data sheet in the repository. The data is originally from here: https://docs.google.com/spreadsheets/d/1qvmwwlUHnQWYc2JQRoE1Qo_IKx6a4CI9ehWIMvkiqFc/edit#gid=577699666

**Comment by LinuxIsCool** [comment]
The 'Historic' and 'Optimistic' projection formulas where made by Griff in the above data sheet. They can be ported into tech.py as a kind of 'data cleaning' function at the beginning of the modelling 'pipeline'.
