### ISSUE TITLE
Add deploy script for deploying to Dynos on Heroku

### ISSUE THREAD

**Issue by LinuxIsCool** [TECommons/Token-Log-Hatch-Params#14]
This will make for an awesome contribution to the TE public goods! It will make for a good example of how to deploy python panel dashboards for cadCAD projects.

**Comment by marthendalnunes** [comment]
By now its deployed on my branch: https://github.com/marthendalnunes/Token-Log-Hatch-Params/tree/marthendalnunes/website.
It can be accessed on https://dev-tec-dash-demo.herokuapp.com/app.
