### ISSUE TITLE
Design a very specific output that should be exported to a github issue

### ISSUE THREAD

**Issue by GriffGreen** [TECommons/Token-Log-Hatch-Params#17]
When the token model is designed, there needs be a clear output with these requirements:

1. It summarizes the results of the parameter choices showing the results for if we hit the Minimum raise, the target raise, 500k, 1 mil and 2 mil (potentially other results as well?)

2. It should be easy to take the outputs and repost them as a github issue for token log voting.

3. It should be easy to take the outputs and redesign your own Commons, with an attribution chain shown as an output (These params were first proposed by YGG, then Jake forked them, then Griff forked Jake, then Vitor forked Griff).

Submitting results should be a 2-step process, compile results, submit for voting

Details about the outputs can be seen here: 
https://www.notion.so/TEC-Models-Spec-d24bdea227324576b04c88871aa616c4

**Comment by GriffGreen** [comment]
related to https://github.com/TECommons/Token-Log-Hatch-Params/issues/11

**Comment by marthendalnunes** [comment]
I think it could be:

- User comments (already implemented)
- Results summary (already implemented)
- Table with all the parameters (PR is open, needs @mendesfabio review)
- Table with different scenarios of total raised, as discussed on #51 ((PR is open, needs review)
- All charts as images, less the impact hour accumulation curve, that is static (related to #52 and #53)

@GriffGreen  do you think that something else is missing?
