### ISSUE TITLE
Simplify things by removing the ability to choose Impact Hour Params

### ISSUE THREAD

**Issue by GriffGreen** [TECommons/Token-Log-Hatch-Params#19]
Impact hour range is a thing... but it should be determined at the time of launching the vote and an assumption for a projected impact hours should be made so that it is consistent for every submission

<img width="281" alt="Screen Shot 2021-02-07 at 3 07 50 PM" src="https://user-images.githubusercontent.com/14945613/107158176-928b3f00-6988-11eb-8dc1-cb058a538a6f.png">

**Comment by marthendalnunes** [comment]
@GriffGreen what do you mean here is to keep showing the total impact hours, but estimating a fixed value and not allowing the users to change it?
