### ISSUE TITLE
Make an output graph that runs thru various scenarios of Hatch Raise Amounts

### ISSUE THREAD

**Issue by GriffGreen** [TECommons/Token-Log-Hatch-Params#22]
This is very well stated in here: https://www.notion.so/TEC-Models-Spec-d24bdea227324576b04c88871aa616c4

For various raise amounts state similar data:

1. IH Rate:
    1. How much money do I get for my IH?
2. Cultural Build Tribute:
3. Percentage of Funds Redeemable by Hatcher:  FR = FH*(1-H)/(1+C)

**Comment by GriffGreen** [comment]
This is a 3 line chart 

X axis would be amount raised 

Lines start at min raise..

Y axis is doubled.... 
1. %: a % for Cultural Build Tribute and a % for Funds redeemable by hatcher 
2. wxdai/IH

This could also be 3 different graphs if necessary....

**Comment by GriffGreen** [comment]
COnsider running by @markoprljic if we should have 1 graph or 3

**Comment by markoprljic** [comment]
@marthendalnunes Is this for the hatch dashboard? https://tec-hatch-demo.herokuapp.com/app

**Comment by marthendalnunes** [comment]
@markoprljic yeah, this is the dashboard that we have looked at the last week
