### ISSUE TITLE
All parameters need units

### ISSUE THREAD

**Issue by GriffGreen** [TECommons/Token-Log-Hatch-Params#25]

**Comment by marthendalnunes** [comment]
https://github.com/holoviz/panel/issues/1102

**Comment by marthendalnunes** [comment]
@mendesfabio in case the `symbol` param doesn't work to add units, we can use the label parameter of param as below:
`hour_slope = param.Number(0.012, bounds=(0,1), step=0.001, label="Impact hour slope (xDAI)")`
This will result in the following output on the dashboard:
![image](https://user-images.githubusercontent.com/18421017/108367338-1ee30080-71d8-11eb-9ba1-8185e5630075.png)
