### ISSUE TITLE
Maximum impact hour rate doesnt change... is it cause its small???

### ISSUE THREAD

**Issue by GriffGreen** [TECommons/Token-Log-Hatch-Params#29]

**Comment by marthendalnunes** [comment]
test this out with bigger numbers to check and do a sanity check with https://www.desmos.com/calculator/r8kq0r6e2s

**Comment by marthendalnunes** [comment]
I've checked with https://www.desmos.com/calculator/r8kq0r6e2s?lang=pt-BR and it's correct. The max impact hour rate doesn't seem to change much the curve shape because we're using way small values of hour slope, and the amount raised.
