### ISSUE TITLE
Replace the Bar chart with 3 pie charts: Min, Target and Max

### ISSUE THREAD

**Issue by GriffGreen** [TECommons/Token-Log-Hatch-Params#37]
In the end we will have 4 pie charts but only display the 3 smaller ones and the max raise and cap raise are both called Max Raise

Include the absolute value and the %

**Comment by marthendalnunes** [comment]
https://github.com/holoviz/holoviews/issues/4800

**Comment by GriffGreen** [comment]
interesting... well for now I guess we just leave the bar chart...

**Comment by GriffGreen** [comment]
![Screen Shot 2021-02-21 at 2.22.22 PM.png](https://images.zenhubusercontent.com/597b3dc4f8b79f8376e1224b/60be0018-2e81-41d0-a8d5-628b7eb89f94)


Can we replace this with a little 3.14159...
