### ISSUE TITLE
Min, Max, Target raise sliders, attached to eachother but listed twice

### ISSUE THREAD

**Issue by LinuxIsCool** [TECommons/Token-Log-Hatch-Params#5]
Remove the double parameters for min, max, and target raises, and make the sliders use absolute numbers (like in the IH formula vis) rather than relative scales (Like in the Hatch vis).

**Comment by GriffGreen** [comment]
Both should be identical

**Comment by marthendalnunes** [comment]
Find a way so that the classes talk to each other

**Comment by GriffGreen** [comment]
We might need to take some key params out of the Class... make them above the other classes... 

Min Max raise and Target Raise for sure... Maybe others?

Total IH is Static.

**Comment by GriffGreen** [comment]
Move the Min Max raise and Target Raise to the top! :-D
