### ISSUE TITLE
It is taking WWWWAAAAAYYYYY too long to load the dashboard on the website

### ISSUE THREAD

**Issue by marthendalnunes** [TECommons/Token-Log-Hatch-Params#54]
It is taking 5-6 seconds to load the plots and sliders after rendering the header. Think of some solution to mitigate this load time, since the first time the website is open, the params are default, thus the same data will be loaded every single time. Hint: caching inspiration [here.](https://discourse.holoviz.org/t/caching-expensive-python-function-calls-in-panel/1259)

**Comment by GriffGreen** [comment]
Cache every proposal made so the page loads faster...

**Comment by GriffGreen** [comment]
https://tec-hatch-demo.herokuapp.com/

**Comment by marthendalnunes** [comment]
![image](https://user-images.githubusercontent.com/18421017/109431865-511a0c80-79e7-11eb-971a-3cb738d097c8.png)

**Comment by marthendalnunes** [comment]
Test Numba and Dask

**Comment by marthendalnunes** [comment]
@mendesfabio test the cache PR to check if it works #70

**Comment by freedumbs00** [comment]
@marthendalnunes found a solution in a config file for running this faster.
