### ISSUE TITLE
Change website to a custom domain

### ISSUE THREAD

**Issue by marthendalnunes** [TECommons/Token-Log-Hatch-Params#55]
We need to change the current Heroku domain https://tec-hatch-demo.herokuapp.com/app to the following custom domains:
Test hatch domain: http://params.tecommons.org/test-hatch
Hatch domain: http://params.tecommons.org/hatch
Commons upgrade domain: http://params.tecommons.org/commons-upgrade

**Comment by mendesfabio** [comment]
It's live at http://params.tecommons.org/hatch! 😄
