### ISSUE TITLE
Lock the Side Panel so that it doesnt let the user just screw up the view entierly

### ISSUE THREAD

**Issue by GriffGreen** [TECommons/Token-Log-Hatch-Params#58]
![Screen Shot 2021-02-21 at 2.17.58 PM.png](https://images.zenhubusercontent.com/597b3dc4f8b79f8376e1224b/655db40e-c63d-4a07-97e8-eb473656d07a)

**Comment by freedumbs00** [comment]
Work In Progress.   Will find someone else to help.

**Comment by mendesfabio** [comment]
Actually, it's fixed after the dashboard redesign.

**Comment by freedumbs00** [comment]
Woohoo.  Closing this
