### ISSUE TITLE
Rename all parameters to match the final consensus names

### ISSUE THREAD

**Issue by GriffGreen** [TECommons/Token-Log-Hatch-Params#79]
https://docs.google.com/spreadsheets/d/1NBizA4mbj4iFuTkcfg3M1Q7v-9exhMcja8u2BshV5V8/edit#gid=0

**Comment by freedumbs00** [comment]
@divine-comedian  How far are you on this with what you have taken on?  The forum posts and the dashboard?  @GriffGreen Did you do any more after the Spec?

**Comment by freedumbs00** [comment]
closing issue.
